<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>E:\Release_BrunoGUI_Stockfish_1_05\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>7</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>625E199B00B549DD54C669937E9466BC84E25273</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>BrunoGUI_Stockfish_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Resources\FichierrOuvrir.bmp" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 et x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="stockfish\stockfish.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ComponentFactory.Krypton.Toolkit" Version="1.0.0" />
    <PackageReference Include="Krypton.Navigator" Version="95.25.10.293" />
    <PackageReference Include="Krypton.Ribbon" Version="95.25.10.293" />
    <PackageReference Include="Krypton.Toolkit" Version="95.25.10.293" />
    <PackageReference Include="Krypton.Workspace" Version="95.25.10.293" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AideBrunoGUI.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\baron30.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_french_defense.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_italian.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_scottish.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_sicilian_defense.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_slavic_defense.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Big_spanish.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Book.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\codekiddy.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\DCbook_large.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Elo2400.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\final-book.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\gavibook.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\gm2600.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\komodo.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\KomodoVariety.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\Performance.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\rodent.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BibliothèquesPolyglot\varied.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="BrunoGUI.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Bruno_NB.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Moteurs_UCI\Rodent_IV\rodent-iv-x64.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Moteurs_UCI\sargon1978\sargon1978_1_01b.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="rodent.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>